### ISSUE TITLE
Defining multiple handlers 

### ISSUE THREAD

**Issue by prabello** [spreedly/kaffe#100]
I would like to know if it's possible to define multiple handles so I can separate my topics from consumers.

For example, if i do something like this:
```
config :kaffe,
  consumer: [
    heroku_kafka_env: true,
    topics: ["topic1", "topic2"],
    consumer_group: "my-group",
    message_handler: MyHandlerModule,
    worker_allocation_strategy: :worker_per_topic_partition,
  ]
```
My `topic1` and `topic2` messages will be consumed by `MyHandlerModule`, I would like to have one handler for each, is it possible?

**Comment by objectuser** [comment]
@prabello That's currently not possible, unfortunately. You'd have to divide them out within your handler module.

Something we've talked about for a long time is making the configuration generally more flexible. However, we've never found time to work on it.
