### ISSUE TITLE
worker_per_topic_partition with multiple topics

### ISSUE THREAD

**Issue by prabello** [spreedly/kaffe#101]
From my understading when using 
```
worker_allocation_strategy: :worker_per_topic_partition
```
I'll have one worker for each partition my topic has, so if I have 10 partitions, 10 workers will be spawned to consumed messages.

If i do something like:
```
config :kaffe,
  consumer: [
    heroku_kafka_env: true,
    topics: ["topic1", "topic2"],
    consumer_group: "my-group",
    message_handler: MyHandlerModule,
    worker_allocation_strategy: :worker_per_topic_partition,
  ]
```

And topic1 and topic2 both have 10 partitions, does that mean I'll have 20 workers and each worker will deal with one partition or do I have 10 workers that are shared for both topics?

**Comment by objectuser** [comment]
The `:worker_per_topic_partition` will allocate one worker per (topic x partition). So it's exactly what you say, 20 workers if you have two topics, each with 10 partitions.

The other strategy, `:worker_per_partition` allocates one worker per partition number across all topics. This is useful if you want to ensure that work across topics is serialized with respect to a partition. This might be more common when you have messages representing the same entity consistently assigned to partitions.
