### ISSUE TITLE
Not pulling earliest messages from topic

### ISSUE THREAD

**Issue by mrezentes** [spreedly/kaffe#16]
In local development, using dev-services:

* set a new consumer group
* ensure that `start_with_earliest_message: true`

When the consumer is started, kaffe does not return the existing messages. 

A work around in development has been to simply start my core seeder and use those messages.

**Comment by dtykocki** [comment]
I've never been able to reproduce this on a local setup. Will reopen if we encounter again.

**Comment by mrezentes** [comment]
I have no idea why I still have access to kaffe. :trollface:  I can no longer reproduce this locally. :trollface:

**Comment by dtykocki** [comment]
It's open source now! 🎉
