### ISSUE TITLE
Handle no_available_offsets

### ISSUE THREAD

**Issue by objectuser** [spreedly/kaffe#23]
Received a bad match:

```
no match of right hand side value: {:error, {{:badmatch, {:error, :no_available_offsets}}, [{Kaffe.Subscriber, :init, 1, [file: 'lib/kaffe/group_member/subscriber/subscriber.ex', line: 50]}, {:gen_server, :in...
```

Need to find out what it means and what to do about it.

**Comment by objectuser** [comment]
This error would come through from Brod when fetching the offsets when subscribing.

**Comment by rwdaigle** [comment]
Do we have info on what this exception means? E.g. is it a transient thing or something more foundational?

**Comment by objectuser** [comment]
The error is [produced by Brod](https://github.com/klarna/brod/blob/master/src/brod_consumer.erl#L604) any time offsets can't be fetched. [One of those times](https://github.com/klarna/brod/blob/master/src/brod_consumer.erl#L449) is when the offset is reset. I'm expecting this to be a corollary to `OffsetOutOfRange`, which occurs in the worker, when I get to that.

Brucke, which provides some of the model for the Kaffe subscriber, does handle [those classes of errors](https://github.com/klarna/brucke/blob/master/src/brucke_subscriber.erl#L109) as transient or otherwise recoverable.
