### ISSUE TITLE
Worker should compute offset to ack

### ISSUE THREAD

**Issue by objectuser** [spreedly/kaffe#26]
Some consumers have lost messages. This might be due to the consumer. However, it would be easier to reason about the offset to ack if the worker computed it and then sent it on to the subscriber instead of the subscriber storing the information in process state.

This would probably mean removing the computation [from here](https://github.com/spreedly/kaffe/blob/master/lib/kaffe/group_member/subscriber/subscriber.ex#L65) and moving it before [this line](https://github.com/spreedly/kaffe/blob/master/lib/kaffe/group_member/worker/worker.ex#L36).

**Comment by rwdaigle** [comment]
@objectuser is there any way to reproduce this issue? In absence of reproducible test case it might feel like a game of whack a mole...?

**Comment by objectuser** [comment]
@rwdaigle I've not found a way to reproduce it, if it even is an issue. I don't see a problem with the logic, but I think moving the computation would make it easier to understand where the offsets are coming from.

**Comment by objectuser** [comment]
Fixed with https://github.com/spreedly/kaffe/commit/1b36d4be0456984fbab99c66810b34f1b2929f55.
