### ISSUE TITLE
Handle OffsetOutOfRange error

### ISSUE THREAD

**Issue by objectuser** [spreedly/kaffe#27]
When the offset expires or the topic is recreated:

```
ArgumentError: expected argument to be a literal atom, literal keyword or a :kafka_message_set record, got runtime: {:kafka_fetch_error, "topic", 1, :OffsetOutOfRange, "The requested offset is not within the range o...
```

**Comment by objectuser** [comment]
Might be able use [`auto.offset.reset`](https://kafka.apache.org/documentation/#newconsumerconfigs).

That could be a Kaffe client config.

**Comment by rwdaigle** [comment]
Ah, yes! Seems perfect for our use-case.

**Comment by objectuser** [comment]
Fixed with https://github.com/spreedly/kaffe/commit/1b36d4be0456984fbab99c66810b34f1b2929f55.
