### ISSUE TITLE
Update to brod 2.4.1

### ISSUE THREAD

**Issue by sdball** [spreedly/kaffe#29]
In 2.3.4 brod fixed a "block forever" race condition that would cause the brod client to become unresponsive. We should go ahead and get updated to the latest version: 2.4.1.

**Comment by sdball** [comment]
@objectuser It looks like brod has some new settings based around controlling brod's internal buffering of messages. Maybe they could be used to make our message production more efficient.

**Comment by objectuser** [comment]
@sdball I had looked at those previously. If I understand them correctly, it's like implicit buffering. If we used them, we could potentially ack and offset, crash and not write the messages.

Is that your understanding?

**Comment by sdball** [comment]
@objectuser Yes that's possible, depending on how we control the ACKs back to Kafka. We'd want to ensure we only ACK the highest offset that we can definitively place at the end of a contiguous block of offsets.

Or write missed offsets to another system to be individually fetched and replayed?

**Comment by sdball** [comment]
To be clear, these new fields only come into play if we use `:brod.produce_async`

**Comment by objectuser** [comment]
@sdball Based on the quoted reasoning I was thinking they could also be used with `:brod.produce_sync`:

> 2. Not to surprise `brod:produce_sync` callers

But maybe I'm misinterpreting.

Still, I think `brod:produce_sync` with some batching is a good next step!

**Comment by sdball** [comment]
Oh I think you're right! Ah yes I even saw that behavior locally when I testing buffering vs not. When you produce sync from separate processes brod can allow things to buffer internally or not.

**Comment by objectuser** [comment]
Kaffe currently supports the latest Brod.
