### ISSUE TITLE
Batch produce to a partition

### ISSUE THREAD

**Issue by rodrigosaito** [spreedly/kaffe#37]
There's currently no way to batch produce to a specific partition, something like:

* `topic/partition/message_list`
```elixir
Kaffe.Producer.produce_sync("topic", 2, [{"key1", "value1"}, {"key2", "value2"}])
```

I can work on this and send a PR, is this something that you would merge back into `kaffe`? Or is there a reason to not having this feature?

Thanks

**Comment by objectuser** [comment]
@rodrigosaito You're right, that's not supported directly. You might be able to configure Kaffe with a function and then use that same function to group your messages before sending, but that's pretty indirect.

Yes, if you would like to submit a PR that delegates to Brod for that behavior, I think that would be a good addition.

Thanks!
