### ISSUE TITLE
[Wishlist] pass the topic name to the messages handler

### ISSUE THREAD

**Issue by dams** [spreedly/kaffe#51]
Hi,

Wouldn't it make sense to pass the topic name to the handle_messages function ? You can configure kafee to consume from multiple topics, so some people might want to do different things based on the topic name

https://github.com/spreedly/kaffe/blob/2b97bdb5d06e39c837d55e99dff85c18addd86e9/lib/kaffe/group_member/worker/worker.ex#L33

thanks

**Comment by objectuser** [comment]
@dams Hi. The topic is part of [each message passed](https://github.com/spreedly/kaffe/blob/master/lib/kaffe/group_member/subscriber/subscriber.ex#L138). The partition is also there.

**Comment by dams** [comment]
Oh I somehow missed that, thanks !
