### ISSUE TITLE
Not all partitions are processed

### ISSUE THREAD

**Issue by athal7** [spreedly/kaffe#53]
I was seeing some odd behavior where one topic in a consumer group being processed fully, but on another topic, a few of the partitions are completely ignored for a good while (even after the other partitions have no lag). 

I'm not sure why, but lowering the max_bytes from the default to `100_000` helped resolve this issue.

I'm on kaffe 1.4.0, elixir 1.5.2. Running in an umbrella app under an erlang release created by distillery. 2 Kafka nodes, 2 nodes of my application, 2 topics, each with 10 partitions.

**Comment by objectuser** [comment]
@athal7 Thanks!

We've not seen this issue ourselves. I wonder if anyone else has. Most of our apps listen to multiple topics, but most (but not all) also specify the `max_bytes` parameter.

You mention lowering it: was it set but set to the same as the default (1,000,000)?

**Comment by athal7** [comment]
It was not previously specified, I was just comparing to the default value when I said lowering. Sorry for the confusing wording

**Comment by objectuser** [comment]
Not at all, just clarifying.

**Comment by athal7** [comment]
I'm seeing this happen again, even with the max bytes specification:

```
$ /opt/kafka/bin/kafka-run-class.sh kafka.admin.ConsumerGroupCommand --bootstrap-server [redacted] --new-consumer --group mygroup --describe | grep mytopic

mytopic           0          -               9782            -          'mygroup@somehost'                 'mygroup@somehost'
mytopic           4          -               9076            -          'mygroup@somehost'                 'mygroup@somehost'
mytopic           8          -               9078            -          'mygroup@somehost'                'mygroup@somehost'
mytopic           1          -               9074            -          'mygroup@somehost'                 'mygroup@somehost'
mytopic           5          -               9076            -          'mygroup@somehost'                 'mygroup@somehost'
mytopic           9          -               9076            -          'mygroup@somehost'                 'mygroup@somehost'
mytopic           2          -               9076            -          'mygroup@somehost'                 'mygroup@somehost'
mytopic           6          9079            9079            0          'mygroup@somehost'                 'mygroup@somehost'
mytopic           3          -               9075            -          'mygroup@somehost'                  'mygroup@somehost'
mytopic           7          -               9075            -          'mygroup@somehost'                  'mygroup@somehost'
```

**Comment by athal7** [comment]
oddly it eventually processed, about 30 minutes after sending this

**Comment by objectuser** [comment]
@athal7 It would be interesting to try to distill this down to a simple test so we could pinpoint the problem: Kaffe, Brod, Kafka, app code ... would be great to get to the bottom of this!

I wonder if you could try to reproduce it in a unit test.

**Comment by athal7** [comment]
@objectuser agreed that that would be useful, curious if you have any ideas on how to go about that? It seems like one of those problems to me that is dependent on timing and amount of data, but could be wrong.

**Comment by objectuser** [comment]
It does not seem easy! 

My only thought is to run batches of known data to a topic and read from it, noting how long it takes to consume the full set. If we can at least reproduce it after X iterations, maybe we can start bisecting the code to see where it all happens.

Maybe each batch could be a set of random numbers (enough for 10 or 100 keys per partition). Those could be sent through and the consumer could collect the data until all data is accounted for.

What do you think?

**Comment by athal7** [comment]
We haven't seen this recently, closing.
