### ISSUE TITLE
_group_config = [] ?

### ISSUE THREAD

**Issue by stephanos** [spreedly/kaffe#66]
Today I noticed that my `offset_commit_interval_seconds` setting wasn't picked up. And did some digging and found that in `group_member.ex:46` it says

```
{:ok, pid} = group_coordinator().start_link(subscriber_name, consumer_group,
      [topic], _group_config = [], __MODULE__, self())
```

Why is `_group_config = []` there? That's the reason `offset_commit_interval_seconds` isn't propagated to brod. Why isn't it taking the group config from kaffe's configuration?

**Comment by objectuser** [comment]
@stephanos It looks like that setting is only relevant if we also used `offset_commit_policy: commit_to_kafka_v2`. Currently, Kaffe commits offsets after the `handle_messages` function is returned. I don't think it would be possible to support that option without other changes to Kaffe.

Am I understanding that correctly?

**Comment by objectuser** [comment]
Outside of this specific question, though, we should see which of those properties we could support (assuming I'm reading things right in this case).

**Comment by stephanos** [comment]
🤔I don't know enough about brod or kaffe to answer that question.

What I found was that in an integration test that sent a message to Kafka and _waited_ for it to be acked in Kafka  _always_ took exactly 5s. I could see that the message was acked in our handler code but it was only _sent_ to Kafka every 5s. This matches exactly the default time for `offset_commit_interval_seconds` so my naive assumption was that I can just lower that setting to 100ms during testing. But, to my surprise, it didn't do anything. So - only from what I observed - I think this setting is useful and is being used _right now_.

**Comment by objectuser** [comment]
Very interesting! Do you want to try to pass it in and see if you get the results you expect?

Looking at the definition of `consumer_group_config` [here](https://github.com/spreedly/kaffe/blob/master/lib/kaffe/config/consumer.ex#L38), I do think you're on to something.

I think you'd just need to grab the config like this:

```
  defp group_config do
    Kaffe.Config.Consumer.configuration.group_config
  end
```

Having it verified in your test would ensure that it would do the right thing.

**Comment by stephanos** [comment]
I just tried it: I can see that my test went from ~5s to 1s! The ack is definitely sent faster now.

This is all I changed:

```
{:ok, pid} = group_coordinator().start_link(subscriber_name, consumer_group,
      [topic], group_config(), __MODULE__, self())
```
and
```
defp group_config do
    Kaffe.Config.Consumer.configuration.group_config
 end
```
as well as
```
config :kaffe,
  consumer: [
    rebalance_delay_ms: 100,
    offset_commit_interval_seconds: 1,
    endpoints: [localhost: 9092]
  ],
  ...
```

**Comment by objectuser** [comment]
@stephanos Excellent! Would you be interested in submitting a PR? I think this is a nice addition.

**Comment by stephanos** [comment]
I will!

**Comment by stephanos** [comment]
closed, continued in https://github.com/spreedly/kaffe/pull/70
