### ISSUE TITLE
Allow runtime configuration of consumers.

### ISSUE THREAD

**Issue by keathley** [spreedly/kaffe#74]
This is similar to the proposal @scrogson made in #73. It would be very nice if we could pass configuration to the consumers when they start, like:

```elixir
consumer_config =   [
    endpoints: [kafka: 9092], # that's [hostname: kafka_port]
    topics: ["interesting-topic"], # the topic(s) that will be consumed
    consumer_group: "your-app-consumer-group", # the consumer group for tracking offsets in Kafka
    message_handler: MessageProcessor, # the module from Step 1 that will process messages

    # optional
    async_message_ack: false, # see "async message acknowledgement" below
    start_with_earliest_message: true # default false
  ]

children = [
  {Kaffe.Consumer, consumer_config},
]
```

This would play nicer with releases and support other use cases such as dynamically starting consumers. This is something that we occasionally need to do to read error topics or re-constitute some state.

**Comment by scrogson** [comment]
Another thing that would be really nice is if the consumer and producer were behaviours similar to `GenServer`. 

```ex
defmodule MyApp.Consumer do

  def start_link(config, opts \\ []) do
    Kaffe.Consumer.start_link(__MODULE__, config, opts)
  end

  def handle_messages(messages, state) do
    ...
  end
end
```

I can’t believe I typed all that on my phone... 😀

Then you could start your own module

**Comment by davidsantoso** [comment]
> I can’t believe I typed all that on my phone... 

well now I feel like we should do it just based on that effort! 😸

**Comment by davidsantoso** [comment]
👍 thanks for all the suggestions. Going to try and carve out some time this week and next to groom the project a bit and see what we can refactor.

**Comment by davidsantoso** [comment]
@keathley based on your code snippet, curious if y'all use/prefer single message consumers more than the `Kaffe.GroupMember` setup to do batch message processing?

**Comment by fatcatt316** [comment]
Closing due to above PR

**Comment by lud** [comment]
Hi, 

It seems that this change did not make it to the current master of Kaffe. Currently there is no way to set configuration at runtime when starting the supervision tree, everything must be known up front.
