### ISSUE TITLE
Support connecting to Confluent Kafka

### ISSUE THREAD

**Issue by krgn** [spreedly/kaffe#84]
I'd like to connect to Confluent Cloud's managed Kafka clusters using this library, but its proving to be tricky. The following producer config does currently not work with confluent cloud:

```
config :kaffe,
  ...
  producer: [
    # [hostname: port]
    endpoints: ["my-confluent-cloud-host": 9092],
    topics: ["test-topic"],

    # optional
    partition_strategy: :random,
    sasl: %{
      mechanism: :plain,
      login: "xxxxxxxxxxxxxxxx",
      password: "xxxxxxxxxxxxxxxx"
    }
  ]
```

The error I get is: 

```
iex(1)>
15:56:38.906 [error] Failed to connect to my-confluent-cloud-host:9092                                                  
Make sure 'ssl' option is in client config, 
or make sure connecting to 'SASL_PLAINTEXT://' listener
```

This bubbles up from `kafka_protocol` (see: https://github.com/klarna/kafka_protocol/blob/master/src/kpro_connection.erl#L542) and is because confluent expects `SASL_PLAIN`, i.o.w. `SASL` over `SSL`. 

I see there is support for Heroku, but I don't have a cert/key from confluent I can use. Do I need to generate this myself? Is confluent cloud generally supported?

**Comment by objectuser** [comment]
@krgn I'm not aware of others using Kaffe with Confluent Cloud. The SASL support is quite new and might be target specific.

**Comment by andyleclair** [comment]
Hi, just to chime in, I'm also having this same issue. If I can figure it out, I'll be certain to update here!

**Comment by andyleclair** [comment]
Hi! So, I've managed to get this to work with raw `brod` (3.7) and now I'm going to set about trying to mash the bits I need into (probably) a fork of Kaffe.

FWIW, this is the config that's worked for me _for just brod_.

```
config :brod,  producer: [
   endpoints: [{"your-url.aws.confluent.cloud", 9092}],
   sasl: {
      :plain,
      "username",
      "password"
    },
  ]
```

Then in the test client code:

```elixir
  def start_producer() do
    config = Application.get_env(:brod, :producer)
    topic = Application.get_env(:brod, :topic)
    sasl_config = config[:sasl]

    if sasl_config do
      # Staging and Prod are configured to talk to the prod Kafka cluster
      client =
        :brod.start_client(
          config[:endpoints],
          @client_name,
          sasl: sasl_config,
          ssl: true
        )

      :brod.start_producer(@client_name, topic, [])
    else
      # Localhost needs to not use sasl or ssl
      client = :brod.start_client(config[:endpoints], @client_name, [])
      :brod.start_producer(@client_name, topic, [])
    end
  end
```

The code's a little crappy rn, but I got this to work about 20 minutes ago, don't harsh on me too hard

**Comment by andyleclair** [comment]
I think the biggest thing that needs to happen here is to support the `ssl: true` option that brod supports

**Comment by andyleclair** [comment]
Left a PR over here: https://github.com/spreedly/kaffe/pull/88

**Comment by objectuser** [comment]
PR #88 is merged. Thank you @andyleclair!

@krgn It would be awesome if you could test this out as well.
