### ISSUE TITLE
Brod consumers terminating

### ISSUE THREAD

**Issue by andyleclair** [spreedly/kaffe#89]
Hi again!

I'm not sure if this is expected or regular, but I'm seeing a lot of this in my logs (with the single consumer, not group consumer or message batching)

```
[warn] :brod_consumer #PID<0.479.0> terminating, reason:
{{:badmatch, []}, [{:brod_consumer, :handle_fetch_response, 2, [file: 'src/brod_consumer.erl', line: 345]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 637]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 711]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}
[error] GenServer #PID<0.479.0> terminating
** (MatchError) no match of right hand side value: []
    (brod) src/brod_consumer.erl:345: :brod_consumer.handle_fetch_response/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:msg, #PID<0.454.0>, {:kpro_rsp, :fetch_response, 3, 6, [throttle_time_ms: 4894, responses: []]}}
State: {:state, #PID<0.420.0>, #PID<0.454.0>, "events", 4, 25972, 10000, 0, 1048576, 1000, 10, 6, #PID<0.419.0>, #Reference<0.3419544911.997457921.8525>, {:pending_acks, 0, 0, {[], []}}, false, :reset_by_subscriber, 1182.0585739109188, 1048576, 5, 102400}
```

Should this concern me? Obviously, it recovers and processes more messages, but it generally fails after _some_ amount of time.

**Comment by objectuser** [comment]
@andyleclair I'm not sure I've seen that particular error. Is it failing to get messages from Kafka itself and getting a response it's not coded to handle? The Brod consumer that is? 🤔

**Comment by andyleclair** [comment]
I'm not sure! From looking at the brod code, it looks like it was trying to pattern match on an empty message, but my erlang isn't the best. Maybe I should open an issue there?

I'm going to try using a group consumer rather than the single consumer and see how that goes.

**Comment by objectuser** [comment]
Are you using `Kaffe.Consumer`? You most definitely want to switch to `Kaffe.GroupMemberSupervisor`. The former is slow and no one uses it. The latter is fast and scales.

I need to update the README and just deprecate the `Kaffe.Consumer`.

**Comment by andyleclair** [comment]
ah, that would probably do it! I'll close this and give that a shot. Thanks so much. If I can help out with the Readme, please let me know. Thank you for Kaffe, we're having a great experience in general with it
